// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3MLlaak1gskTQNbeEaRxvPq1kczCcIdw',
    appId: '1:687249603592:web:8411b3c3d34b881c6c65bd',
    messagingSenderId: '687249603592',
    projectId: 'technici-5f45d',
    authDomain: 'technici-5f45d.firebaseapp.com',
    storageBucket: 'technici-5f45d.firebasestorage.app',
    measurementId: 'G-6QRTCEMKP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOMxjWZXypPjQM6ic0ug8mcHIK7uXNGwk',
    appId: '1:687249603592:android:75c5c51535ad67376c65bd',
    messagingSenderId: '687249603592',
    projectId: 'technici-5f45d',
    storageBucket: 'technici-5f45d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORFF9yoM4tojBhGAIOOJC9Ejse-LseDQ',
    appId: '1:687249603592:ios:b5a35fa3be801dd66c65bd',
    messagingSenderId: '687249603592',
    projectId: 'technici-5f45d',
    storageBucket: 'technici-5f45d.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORFF9yoM4tojBhGAIOOJC9Ejse-LseDQ',
    appId: '1:687249603592:ios:b5a35fa3be801dd66c65bd',
    messagingSenderId: '687249603592',
    projectId: 'technici-5f45d',
    storageBucket: 'technici-5f45d.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3MLlaak1gskTQNbeEaRxvPq1kczCcIdw',
    appId: '1:687249603592:web:8a90e857d39da49e6c65bd',
    messagingSenderId: '687249603592',
    projectId: 'technici-5f45d',
    authDomain: 'technici-5f45d.firebaseapp.com',
    storageBucket: 'technici-5f45d.firebasestorage.app',
    measurementId: 'G-0HQEL80Z2Z',
  );

}